services:
    server:
        build: ./ChatService
        ports:
             - 7891:7891
        networks:
            - some-net
    client:
        build: ./ConsoleApp
        stdin_open: true
        tty: true
        networks:
            - some-net
    client2:
        build: ./ConsoleApp
        stdin_open: true
        tty: true
        networks:
            - some-net
networks:
  some-net:
    driver: bridge

    